<?php

namespace SamGunBundle\Repository;

use Doctrine\ORM\EntityRepository ;

/**
 * SalarieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalarieRepository extends \Doctrine\ORM\EntityRepository
{
  public function get_nb_salaries(){
    $query = $this->createQueryBuilder('s')
              ->select('COUNT(s)')
              ->getQuery();
    $nb = $query->getSingleScalarResult();
    return $nb;
  }

  public function get_nb_femmes(){
    $query = $this->createQueryBuilder('s')
              ->select('COUNT(s)')
              ->where('s.sexe = \'F\' ')
              ->getQuery();
    $nb = $query->getSingleScalarResult();
    return $nb;
  }

  public function get_salarie_annee($date){
    $query = $this->getEntityManager()->createQuery('SELECT COUNT(s) FROM SamGunBundle:Salarie s WHERE s.dateEntre <= ?1');
    $query->setParameters(array(
      1=> new \DateTime($date),
    ));
    $nb = $query->getSingleScalarResult();
    return $nb;
  }


  public function get_role_nb($id){
    $query = $this->getEntityManager()->createQuery('SELECT COUNT(s) FROM SamGunBundle:Salarie s WHERE s.superieurHierarchique = ?1');
    $query->setParameters(array(
      1=> $id,
    ));
    $nb = $query->getSingleScalarResult();
    return $nb;
  }

  public function get_nb_salaire(){
    $query = $this->getEntityManager()->createQuery('SELECT COUNT(s) FROM SamGunBundle:Salarie s WHERE s.salaire > 2000');
    $nb = $query->getSingleScalarResult();
    return $nb;
  }

  public function get_nb_employe($statut){
    $query = $this->getEntityManager()->createQuery('SELECT COUNT(s) FROM SamGunBundle:Salarie s WHERE s.typeContrat = ?1');
    $query->setParameters(array(
      1 => $statut,
    ));
    $nb = $query->getSingleScalarResult();
    return $nb;
  }

  public function get_nb_employe_salaire($salaire){
    $query = $this->getEntityManager()->createQuery('SELECT COUNT(s) FROM SamGunBundle:Salarie s WHERE s.salaire > ?1');
    $query->setParameters(array(
      1 => $salaire
    ));
    $nb = $query->getSingleScalarResult();
    return $nb;
  }
}
