<?php

namespace SamGunBundle\Repository\Forum;

/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesRepository extends \Doctrine\ORM\EntityRepository
{

  public function get_id_by_name($nom_categorie){
    $query = $this->getEntityManager()->createQuery('SELECT c.id FROM SamGunBundle:Forum\Categories c WHERE c.nom = ?1');
    $query->setParameters(array(
      1=> $nom_categorie,
    ));
    $id = $query->getResult();
    return $id;
  }


}
