<?php

namespace SamGunBundle\Repository\Forum;

/**
 * SousCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousCategoriesRepository extends \Doctrine\ORM\EntityRepository
{

  public function get_id_by_name($nom_scategorie){
    $query = $this->getEntityManager()->createQuery('SELECT s.id FROM SamGunBundle:Forum\SousCategories s WHERE s.nom = ?1');
    $query->setParameters(array(
      1=> $nom_scategorie,
    ));
    $id = $query->getResult();
    return $id;
  }

  /*public function findAll_by_cat($id_categorie){
    $query = $this->getEntityManager()->createQuery('SELECT s FROM SamGunBundle:Forum\SousCategories s WHERE s.idCategorie = ?1');
    $query->setParameters(array(
      1=> $id_scategorie,
    ));
    $id = $query->getResult();
    return $id;
  }*/

}
