<?php

namespace SamGunBundle\Repository\Forum;

/**
 * TopicsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicsRepository extends \Doctrine\ORM\EntityRepository{


  public function getTopics($id_categorie,$id_souscategorie){
    $query = $this->getEntityManager()->createQuery(
      'SELECT t,u FROM SamGunBundle:Forum\Topics t , SamGunBundle:Forum\Topics_Categories tc ,
      SamGunBundle:Forum\Categories c , SamGunBundle:Forum\SousCategories sc , SamGunBundle:User u
       WHERE  t.id = tc.idTopic AND tc.idCategorie = c.id AND tc.idSouscategorie= sc.id AND t.idCreateur = u.id
       AND tc.idCategorie = ?1 AND tc.idSouscategorie = ?2');

    $query->setParameters(array(
      1 => $id_categorie,
      2 => $id_souscategorie,
    ));
    //$query = $this->getEntityManager()->createQuery('SELECT t FROM SamGunBundle:Forum\Topics t');

    $topic = $query->getResult();
    return $topic;
  }

  public function getTopics_by_cat($id_categories){
    $query = $this->getEntityManager()->createQuery(
      'SELECT t,u FROM SamGunBundle:Forum\Topics t , SamGunBundle:Forum\Topics_Categories tc , SamGunBundle:User u,
      SamGunBundle:Forum\Categories c
       WHERE  t.id = tc.idTopic AND tc.idCategorie = c.id AND t.idCreateur = u.id
       AND tc.idCategorie = ?1');

    $query->setParameters(array(
      1 => $id_categories,
    ));
    //$query = $this->getEntityManager()->createQuery('SELECT t FROM SamGunBundle:Forum\Topics t');

    $topic = $query->getResult();
    return $topic;
  }

  public function getnbTopicsbycat($id_categorie){
    $query = $this->getEntityManager()->createQuery(
      'SELECT COUNT(t) FROM SamGunBundle:Forum\Topics t , SamGunBundle:Forum\Topics_Categories tc
       WHERE  t.id = tc.idTopic AND tc.idCategorie = ?1');

    $query->setParameters(array(
      1 => $id_categorie,
    ));
    //$query = $this->getEntityManager()->createQuery('SELECT t FROM SamGunBundle:Forum\Topics t');

    $nb = $query->getSingleScalarResult();
    return $nb;
  }

}
