<?php

namespace SamGunBundle\Repository\Forum;

/**
 * Topics_CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Topics_CategoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
